In [1]:
import numpy as np

In [17]:
#matrx sum and difference and scaler sum/dif
#1 dimension
x= np.array([1,2,3])
y= np.array([2,2,2])
summ = x+y
diff = x-y
scaler1 = y+3
scaler2 = y-3

print(">>>",x)
print(">>>",y)
print(">>>",summ)
print(">>>",scaler1)
print(">>>",scaler2)
print("===================")
#multi - dimensional
x=np.arange(6).reshape(2,3)
y=np.ones_like(x)
summ = x+y
diff = x-y
scaler1 = y+3
scaler2 = y-3

print(">>>",x)
print(">>>",y)
print(">>>",summ)
print(">>>",scaler1)
print(">>>",scaler2)
print("===================")

>>> [1 2 3]
>>> [2 2 2]
>>> [3 4 5]
>>> [5 5 5]
>>> [-1 -1 -1]
>>> [[0 1 2]
 [3 4 5]]
>>> [[1 1 1]
 [1 1 1]]
>>> [[1 2 3]
 [4 5 6]]
>>> [[4 4 4]
 [4 4 4]]
>>> [[-2 -2 -2]
 [-2 -2 -2]]


In [27]:
#product ,division,modulo and scaler product/div/mod
#1dimensional: a[a1,a2,a3] * b[b1,b2,b3] =c[a1b1,a2b2,a3b3]. size of both the arrays should be same.
x= np.array([5,5,5])
y= np.array([2,2,2])
prod = x*y
div  = x/y
div2 = x//y
modu = x%y
scaler1 = x*3
scaler2 = x/3
scaler3 = x//3
scaler4 = x%3

print(">>>",x)
print(">>>",y)
print(">>>",prod)
print(">>>",div)
print(">>>",div2)
print(">>>",modu)
print(">>>",scaler1)
print(">>>",scaler2)
print(">>>",scaler3)
print(">>>",scaler4)

print("===================")
# multi dimensional:will be same as 1 dimensionals

x= np.array([5,5,5,5]).reshape((2,2))
y= np.array([2,2,2,2]).reshape((2,2))
prod = x*y
div  = x/y
div2 = x//y
modu = x%y
scaler1 = x*3
scaler2 = x/3
scaler3 = x//3
scaler4 = x%3

print(x)
print(y)
print(prod)
print(div)
print(div2)
print(modu)
print(scaler1)
print("===================")

#mathemetical matrix multiplication : dot products
x= np.array([1,2,2,1]).reshape((2,2))
y= np.array([1,0,0,1]).reshape((2,2))
prod =x.dot(y) #or np.dot(x,y)
print(x)
print(y)
print(prod)




>>> [5 5 5]
>>> [2 2 2]
>>> [10 10 10]
>>> [2.5 2.5 2.5]
>>> [2 2 2]
>>> [1 1 1]
>>> [15 15 15]
>>> [1.66666667 1.66666667 1.66666667]
>>> [1 1 1]
>>> [2 2 2]
[[5 5]
 [5 5]]
[[2 2]
 [2 2]]
[[10 10]
 [10 10]]
[[2.5 2.5]
 [2.5 2.5]]
[[2 2]
 [2 2]]
[[1 1]
 [1 1]]
[[15 15]
 [15 15]]
[[1 2]
 [2 1]]
[[1 0]
 [0 1]]
[[1 2]
 [2 1]]


In [32]:
# checks  : similar to np.ones_like(arr) function , but rather creates an aray of booleans based on the condition and not 1's. it also does not uses any functions

a=np.array([2132,1021,4401,3013,7744,5975])
b= (a%2 != 0)
print(">>>",a)
print(">>>",b)
print("=======================")

a=np.array([2132,1021,4401,3013,7744,5975]).reshape(3,2)
b= (a%2 != 0)
print(a)
print(b)


>>> [2132 1021 4401 3013 7744 5975]
>>> [False  True  True  True False  True]
[[2132 1021]
 [4401 3013]
 [7744 5975]]
[[False  True]
 [ True  True]
 [False  True]]


In [43]:
#other basic  numpy functions
a= np.array([1,2,32,23,12,24])
a_ndim = np.array([1,2,32,23,12,24]).reshape((2,3))

print('>>>',a)
print('>>>',a.min())
print('>>>',a.max())
print('>>>',a.sum())
print('>>>',a.sum(axis=0)) #horizontal direction
#print('>>>',a.sum(axis=1)) #vertical direction. although error for this  since its a 1-d array

print("================\n")


print(a_ndim)

print('>>>',a_ndim.sum())
print('>>>',a_ndim.sum(axis=0)) #vertical direction sum??
print('>>>',a_ndim.sum(axis=1)) #horizontal direction. sum??how??

print('>>>',a_ndim.min())
print('>>>',a_ndim.min(axis=0))
print('>>>',a_ndim.min(axis=1))

print('>>>',a_ndim.max())
print('>>>',a_ndim.max(axis=0))
print('>>>',a_ndim.max(axis=1))


#there are other functions like average(), mod(),etc in array library, check'em out

>>> [ 1  2 32 23 12 24]
>>> 1
>>> 32
>>> 94
>>> 94

[[ 1  2 32]
 [23 12 24]]
>>> 94
>>> [24 14 56]
>>> [35 59]
>>> 1
>>> [ 1  2 24]
>>> [ 1 12]
>>> 32
>>> [23 12 32]
>>> [32 24]
