In [2]:
import numpy as np

In [16]:
a = np.arange(15).reshape([3, 5])
b = a % 2 == 0  #this will generate a 3x5 matrix of trues and falses

print(a)
print(b)
print(a[b])
# this will generate a list of all values  which have true against the condition.
# not that it won't generate the same shaped matrix. rather, it generates a 1d list                          

print(np.count_nonzero(a < 6))
# this actually works after makeing true=1 and false =0
print(np.sum(a < 6))  # simply, sum[1,1,1,1,1,1.00000...]
print(np.sum(a[a < 6]))  #sum of all the numbers for which the condition evealuates to true.

print(np.sum(a<6,axis=1))
# it gives [5,1,0] which is the row-wise sum of :
# [ 1,1,1,1,1              [ T,T,T,T,T    
#   1,0,0,0,0           or   T,F,F,F,F
#   0,0,0,0,0 ]              F,F,F,F,F ]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 0  2  4  6  8 10 12 14]
6
6
15
[5 1 0]


In [19]:
print(a)
print(np.any(a>6)) #is any element greater than 6?
print(np.all(a<12))# are all elements of a <12?

print(np.any(a>6,axis=1)) #is any element greater than 6, row-wise?
print(np.all(a<12,axis=1))# are all elements of a <12,rowise?                             



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
True
False
[False  True  True]
[ True  True False]


In [20]:
#indexing with string structured arrays

In [22]:
#MAKING A CUSTOM N-DIM default ARRAY
"""
-what is a 'custom default' array and how is it custom?
usually if we have to create an array, we 
write x=np.arrange(15).reshape(3,5)
-it generates a 3x5 array with garbage values. we remove 
the garbage using np.zeros(x)
- it thus generates a 3x5 array of 0s. but what  if we
want to pass strings or float to it?
although we know , that python is super flexible , and we cn
simply pass a string at a particular position,But we all
know their must be some auto casting going on under the hood


But wouldn't it be good, if, instead of getting a zero,
the array get's a default value of the datatype 
its about to recieve?like if we knw we have to put
a string in row 1, every element of the row is initalised
by default to '', with datatype = utf-10??

numpy gives us that solution
"""
garbage=None

In [29]:
name = "alisha bhavya chanda diksha".split(' ')
emp_id = [123, 234, 345, 456]
salary = [8.5, 9.03, 8.76, 7.82]

emp_db = np.zeros(
    4,
    dtype={
        'names'  : ('name', 'id', 'sal'),
        'formats': ('U10', 'i4', 'f8')
    }
)
print(emp_db)
#this generates the custom array with custom , pre
# -defined datatypes and custom default values.
# its no harm to add  other data type data to the position
# but this is basically done to add extra features of the
# strict typing languages here.like check these out:


emp_db['name']=name
emp_db['id']=emp_id
emp_db['sal']=salary
print("new database:  ")
print(emp_db)# every name goes in name column, id goes in id column ,... so on!. its like we made alias of every column!
print(emp_db['name'])# we can even access data column wise now in such an easy manner!
print(emp_db[1],emp_db[-1])# row-wise indexing work as usual


[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
new database:  
[('alisha', 123, 8.5 ) ('bhavya', 234, 9.03) ('chanda', 345, 8.76)
 ('diksha', 456, 7.82)]
['alisha' 'bhavya' 'chanda' 'diksha']
('bhavya', 234, 9.03) ('diksha', 456, 7.82)


In [31]:
# let's try a tricky one

print(emp_db[emp_db['sal']>8.6])


[('bhavya', 234, 9.03) ('chanda', 345, 8.76)]
