In [1]:
import sys

print(sys.executable)

C:\ProgramData\Anaconda3\python.exe


In [1]:
#numpy is a cool maths library

import numpy as np
array = np.array([1,2,3,4,5,6])
print(array)


[1 2 3 4 5 6]


In [8]:
array =np.zeros((2,3)) # makes an array of  dimensions with each value =0
print(array)
#a2 =np.zeros((6,5,4,3,2)) # makes an array of 5  dimensions
#print(a2)
a3 =np.zeros((3,3,3)) # makes an array of 5  dimensions
print(a3)


[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [10]:
array =np.ones((2,3)) # makes an array of  dimensions
print(array)
#a2 =np.ones((6,5,4,3,2)) # makes an array of 5  dimensions
#print(a2)
a3 =np.ones((3,3,3)) # makes an array of 5  dimensions
print(a3)


[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
# we can add other datatypes too
a =np.ones((2,3),dtype=np.int16)  # we implied that every element should be a 16 bit integer
print(a)


[[1 1 1]
 [1 1 1]]


In [15]:
#another way to initialise
b= np.empty((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#diagonal matrix( ony diagonal has the values)
diag=np.eye(4) # this always makes a sq matrix
print(diag)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
# numpy has its own range function called arange[a,b,c]
#but unlike range() of py3, it returns a numpy array instead of iterator
n= np.arange(0,50,5) # list of all numbers <=49 divisible by 5
print(n)

#its more cooler tha usual range , because it can take decimal  step too
n2= np.arange(0,2,0.01)# all numbers <=1.99
print(n2)

n3= np.arange((13))**2
print(n3)


[ 0  5 10 15 20 25 30 35 40 45]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11
 1.12 1.13 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25
 1.26 1.27 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39
 1.4  1.41 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53
 1.54 1.55 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67
 1.68 1.69 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81
 1.82 1.83 1.84 1.85 1.86 1.87 1.88 1.89 1.9 

In [21]:
# we can create multi dimensional arrays manually using array([[]])
a= np.array(([1,1,1],[2,2,2],[3,3,3]))
print(a)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [24]:
# we can get dimensions using shape property
print(a.shape)


(3, 3)


In [4]:
#reshape is a function that converts a 1d numpy-array to multi dimensional array
# syntax : reshape(np_arr)--> np_arr
a= np.arange(6)
print(a)
b=a.reshape(2,3)
print(b)

"""
if an array of dimensions a1,a2...an has the product of dimensions as X ,
i.e X=a1*a2*a3*a4*...*an ,and it is being reshaped into another array of 
dimensions p1,p2,p3...pn, then:
p1*p2*...*pn == X == a1*a2*a3*..an

or simply , the product of new dimensions must be equal to total elements
in old array (or product of old array's dimensions)
"""
a=np.arange(10)
print(a)

b=a.reshape(5,2) #correct , since 10==5*2
print(b)

#c=a.reshape(3,4) #wrong
#print(c)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [29]:
#[6-10-18] more on reshaping()                                                                                                             
#1) transposing
x=[
    ['raj','goa','shimla','manali','delhi'],
    ['jai','dis','panaji','shimla','delhi']
]
arr = np.array(x)
print('>>>',arr.__repr__())
#print(arr.shape)

transpose=arr.T #returns a transpose matrix
print(transpose)
#print(transpose.shape)

# 2)reshaping an numpy array into 2d mtrix when total elements are unknow, but we know how many columns/rows are needed
#   ans: use -1 for unknown index. but be warned , other index should be following the rehaping rule

arr=np.array(x).flatten()
print(arr)
arr=arr.reshape(-1,5)
print(arr)
print(arr.reshape(5,-1))


>>> array([['raj', 'goa', 'shimla', 'manali', 'delhi'],
       ['jai', 'dis', 'panaji', 'shimla', 'delhi']], dtype='<U6')
[['raj' 'jai']
 ['goa' 'dis']
 ['shimla' 'panaji']
 ['manali' 'shimla']
 ['delhi' 'delhi']]
['raj' 'goa' 'shimla' 'manali' 'delhi' 'jai' 'dis' 'panaji' 'shimla'
 'delhi']
[['raj' 'goa' 'shimla' 'manali' 'delhi']
 ['jai' 'dis' 'panaji' 'shimla' 'delhi']]
[['raj' 'goa']
 ['shimla' 'manali']
 ['delhi' 'jai']
 ['dis' 'panaji']
 ['shimla' 'delhi']]


In [20]:
# reverse of reshape is flatten
# it flattens the elements row-wise
a = np.arange(9).reshape(3, 3)
print(a)  # very big
a = a.flatten()
print(a)


a = np.arange(24).reshape(4, 3, 2, 1)
print(a)  # very big
b = a.flatten()
print(b) #but a does not change
#print(a)

#another efficient method is ravel()
x=a.ravel()
print('>>>',x)
print('>>>',a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[[[[ 0]
   [ 1]]

  [[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]

  [[10]
   [11]]]


 [[[12]
   [13]]

  [[14]
   [15]]

  [[16]
   [17]]]


 [[[18]
   [19]]

  [[20]
   [21]]

  [[22]
   [23]]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[[ 0]
   [ 1]]

  [[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]

  [[10]
   [11]]]


 [[[12]
   [13]]

  [[14]
   [15]]

  [[16]
   [17]]]


 [[[18]
   [19]]

  [[20]
   [21]]

  [[22]
   [23]]]]
>>> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
>>> [[[[ 0]
   [ 1]]

  [[ 2]
   [ 3]]

  [[ 4]
   [ 5]]]


 [[[ 6]
   [ 7]]

  [[ 8]
   [ 9]]

  [[10]
   [11]]]


 [[[12]
   [13]]

  [[14]
   [15]]

  [[16]
   [17]]]


 [[[18]
   [19]]

  [[20]
   [21]]

  [[22]
   [23]]]]


In [31]:
#to get total elements of a matrix of unknown size or dimensions, function is narray.size                 
arr=np.arange(120).reshape(2,2,5,3,2)
print(arr.size)
print(arr)


120
[[[[[  0   1]
    [  2   3]
    [  4   5]]

   [[  6   7]
    [  8   9]
    [ 10  11]]

   [[ 12  13]
    [ 14  15]
    [ 16  17]]

   [[ 18  19]
    [ 20  21]
    [ 22  23]]

   [[ 24  25]
    [ 26  27]
    [ 28  29]]]


  [[[ 30  31]
    [ 32  33]
    [ 34  35]]

   [[ 36  37]
    [ 38  39]
    [ 40  41]]

   [[ 42  43]
    [ 44  45]
    [ 46  47]]

   [[ 48  49]
    [ 50  51]
    [ 52  53]]

   [[ 54  55]
    [ 56  57]
    [ 58  59]]]]



 [[[[ 60  61]
    [ 62  63]
    [ 64  65]]

   [[ 66  67]
    [ 68  69]
    [ 70  71]]

   [[ 72  73]
    [ 74  75]
    [ 76  77]]

   [[ 78  79]
    [ 80  81]
    [ 82  83]]

   [[ 84  85]
    [ 86  87]
    [ 88  89]]]


  [[[ 90  91]
    [ 92  93]
    [ 94  95]]

   [[ 96  97]
    [ 98  99]
    [100 101]]

   [[102 103]
    [104 105]
    [106 107]]

   [[108 109]
    [110 111]
    [112 113]]

   [[114 115]
    [116 117]
    [118 119]]]]]


In [41]:
a=np.arange(0,54,2).reshape(3,3,3)
print(a)
b=np.ones_like(a) # will create b with same dimensions as that of a , but with only 1's
print(b)


[[[ 0  2  4]
  [ 6  8 10]
  [12 14 16]]

 [[18 20 22]
  [24 26 28]
  [30 32 34]]

 [[36 38 40]
  [42 44 46]
  [48 50 52]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [30]:
a=np.arange(0,54,2).reshape(3,3,3)
print(a)
b=np.empty_like(a) # will create b with same dimensions as that of a , but with only 0's
print(b)


[[[ 0  2  4]
  [ 6  8 10]
  [12 14 16]]

 [[18 20 22]
  [24 26 28]
  [30 32 34]]

 [[36 38 40]
  [42 44 46]
  [48 50 52]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
