In [10]:
import numpy as np

#previous array indexing in array operations -3

# helper functions>>>>>>>>>>>>
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#1d
a = np.array("ab cd ef gh ij kl mn op qr st uv qx yz".split(' '))
print(a)

index_array = [2, 3, 4]
#b = a[index_array] or
b = a[[2, 3, 4]]
print(b, type(b))


['ab' 'cd' 'ef' 'gh' 'ij' 'kl' 'mn' 'op' 'qr' 'st' 'uv' 'qx' 'yz']
['ef' 'gh' 'ij'] <class 'numpy.ndarray'>


In [23]:
#multi dimensional
l = [[10, 20, 30, 40],
     [50, 60, 70, 80],
     [90, 10, 11, 12]]
a = np.array(l,dtype=str)

row = np.array([[0, 0], [2, 2]])
col = np.array([[0, 3], [0, 3]])
b=a[row,col]
print(b)

"""
explaination: we basically wrote b= a[(0,0,2,2),(0,3,0,3)]
but since its a 2d array, therefore we have to map the values to their positions
thus we wrote b ~= a[ [[0,0],[2,2]] , [[0,3],[0,3]] ]

"""

a[row,col]='aa'
print(a)

[['10' '40']
 ['90' '12']]
[['aa' '20' '30' 'aa']
 ['50' '60' '70' '80']
 ['aa' '10' '11' 'aa']]


In [33]:
# testing your skills
arr=np.arange(1,11)**2
print(arr)

idx=[0,2,4,6,8]
print(arr[idx])

arr[idx]=0
print(arr)

arr[idx]=(arr[idx]+3)*5
print(arr)

[  1   4   9  16  25  36  49  64  81 100]
[ 1  9 25 49 81]
[  0   4   0  16   0  36   0  64   0 100]
[ 15   4  15  16  15  36  15  64  15 100]
