In [2]:
import numpy as np
"""
a = np.ones([1, 5], dtype=np.int16)
print(a, a.shape)       # [1,1,1,1,1]
print(a * 5, a.shape)   # [5,5,5,5,5]

this was a simpler broadcasting such that
[x,x,x,x,x] * [y] ==[xy,xy,xy,xy,xy] 
i.e, a simple scaler multiplication

but what if we have to perform :
[                       [
[x,x,x,x,x],            [y1],
[x,x,x,x,x],      *     [y2],
[x,x,x,x,x]             [y3]
]                       ]
??

numpy does it using the following method:
-it replicates all the values horizontally for y till
 the no. of  elements in y matrix is == x . i.e it makes
 something like this: 
 
[                       [
[x,x,x,x,x],            [y1,y1,y1,y1,y1],
[x,x,x,x,x],      *     [y2,y2,y2,y2,y2],
[x,x,x,x,x]             [y3,y3,y3,y3,y3]
]                       ]
 
 
but what if it is something like: 
[                       [
[x,x,x,x,x],            [y1,y4],
[x,x,x,x,x],      *     [y2,y5],
[x,x,x,x,x]             [y3,y6]
]                       ]
??
well, broadcast will NOT happen.

rule:
for a matrix M(a,b)  to perform scaler multiplication
with other matrix N(x,y) is possible only if:
1. x==a
2. y==1 or y==b

"""


'\na = np.ones([1, 5], dtype=np.int16)\nprint(a, a.shape)       # [1,1,1,1,1]\nprint(a * 5, a.shape)   # [5,5,5,5,5]\n\nthis was a simpler broadcasting such that\n[x,x,x,x,x] * [y] ==[xy,xy,xy,xy,xy] \ni.e, a simple scaler multiplication\n\nbut what if we have to perform :\n[                       [\n[x,x,x,x,x],            [y1],\n[x,x,x,x,x],      *     [y2],\n[x,x,x,x,x]             [y3]\n]                       ]\n??\n\nnumpy does it using the following method:\n-it replicates all the values horizontally for y till\n the no. of  elements in y matrix is == x . i.e it makes\n something like this: \n \n[                       [\n[x,x,x,x,x],            [y1,y1,y1,y1,y1],\n[x,x,x,x,x],      *     [y2,y2,y2,y2,y2],\n[x,x,x,x,x]             [y3,y3,y3,y3,y3]\n]                       ]\n \n \nbut what if it is something like: \n[                       [\n[x,x,x,x,x],            [y1,y4],\n[x,x,x,x,x],      *     [y2,y5],\n[x,x,x,x,x]             [y3,y6]\n]                       ]\n??\nwell, b

In [19]:
x = np.array([1, 1, 1, 1, 1])
y = np.array([2, 3, 4, 5, 6])
print(x * y,x.shape)
print(x * 5)
# one-d array has dimensions [length, nothing]

[2 3 4 5 6] (5,)
[5 5 5 5 5]


In [15]:
x = np.ones([4, 3])
y = np.arange(12).reshape([4, 3])
print(x)
print(x * y)
print(x * 5)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [33]:
mat = (np.random.randint(10, 50, 5))
sci = (np.random.randint(10, 50, 5))
sub = np.array([mat, sci])

print(mat, mat.shape)
print(sci, sci.shape)
print(sub, sub.shape)

#grace= np.array([0.05,0.1)]
#print(grace,grace.shape)#[0.05,0.1] ,[1,2]

#print(sub*grace) won't work since broadcasting not possible
#(column size should be either 1 or = sub's column size

grace= np.array([0.05,0.1])
grace=grace.reshape(len(grace),-1)
print("==================")
print(grace,grace.shape)
print(grace*sub)




[14 19 28 44 39] (5,)
[46 49 34 27 28] (5,)
[[14 19 28 44 39]
 [46 49 34 27 28]] (2, 5)
[[0.05]
 [0.1 ]] (2, 1)
[[0.7  0.95 1.4  2.2  1.95]
 [4.6  4.9  3.4  2.7  2.8 ]]


In [26]:
# concatination
#1 using concatinate
a = np.random.randint(1, 99, 5)
b = np.random.randint(1, 99, 5)
print(">>>", a, ">>>", b)
print(">>>", np.concatenate([a, b], axis=0)) #horizontal
#print(">>>", np.concatenate([a, b], axis=1))#vertical # not possible for i-d

print("=========")
a = np.array("a b c d".split(' ')).reshape([2, 2])
b = np.array("f u q e".split(' ')).reshape([2, 2])
print(">>>\n", a)
print(">>>\n", b)
print(">>>\n", np.concatenate([a, b], axis=0)) # vertical(?_?)
print(">>>\n", np.concatenate([a, b], axis=1)) #horizontal(??)


>>> [92 38 58 58 78] >>> [56 51 49 21 45]
>>> [92 38 58 58 78 56 51 49 21 45]
>>>
 [['a' 'b']
 ['c' 'd']]
>>>
 [['f' 'u']
 ['q' 'e']]
>>>
 [['a' 'b']
 ['c' 'd']
 ['f' 'u']
 ['q' 'e']]
>>>
 [['a' 'b' 'f' 'u']
 ['c' 'd' 'q' 'e']]


In [28]:
#2 using stack
a = np.random.randint(1, 99, 5)
b = np.random.randint(1, 99, 5)
c = np.random.randint(1, 99, 5)
print('>>>', a, '>>>', b, '>>>', c)

print(">>>\n", np.stack([a, b, c], axis=0))
print(">>>\n", np.stack([a, b, c], axis=1))


>>> [64 30 73  5 28] >>> [10 22 54 51 45] >>> [94 47 33 46 42]
>>>
 [[64 30 73  5 28]
 [10 22 54 51 45]
 [94 47 33 46 42]]
>>>
 [[64 10 94]
 [30 22 47]
 [73 54 33]
 [ 5 51 46]
 [28 45 42]]


In [35]:
a=np.arange(10)
np.append(a,[222])

a=np.array([1,2,0,0,0,4,40,0])

b=np.nonzero(a)
print(b[0])


[0 1 5 6]
