In [1]:
import numpy as np

In [9]:
#indexing and slicing
arr= np.arange(10)**2
print(">>>",arr)
print(">>>",arr[0])
print(">>>",arr[2:5])
print(">>>",arr[2:10:2])
print(">>>",arr[5:2:-1])
print(">>>",arr[:10:2])
print(">>>",arr[:])

print(">>>",arr[::-1])
print(">>>",arr[-1:-5:-1])
print(">>>",arr[-5:-1])

>>> [ 0  1  4  9 16 25 36 49 64 81]
>>> 0
>>> [ 4  9 16]
>>> [ 4 16 36 64]
>>> [25 16  9]
>>> [ 0  4 16 36 64]
>>> [ 0  1  4  9 16 25 36 49 64 81]
>>> [81 64 49 36 25 16  9  4  1  0]
>>> [81 64 49 36]
>>> [25 36 49 64]


In [14]:
# special type of indexing/slicing , when using n-dim arrays              
a = [['a', 'b', 'c', 'd'], [12, 13, 14, 15], [0, 0, 0, 0]]
arr = np.array(a)
print(">>>", arr.__repr__())
print(">>>", arr.__str__())
print(">>>", arr[0])  #row 0
print(">>>", arr[0, 2])  #row 0 , col 2 i.e cell[0][2]
print(">>>", arr[0, 2])  #row 0 , col 2 i.e cell[0][2]
print(">>>", arr[0:2,1:2])  #row 0:2 i.e roe 0 and 1, col 1:2 i.e col 1   i.e cell [0][1]  and cell[1][1]                                                         
print(">>>", arr[:,1:3]) # all elements of 1 and second column


>>> array([['a', 'b', 'c', 'd'],
       ['12', '13', '14', '15'],
       ['0', '0', '0', '0']], dtype='<U2')
>>> [['a' 'b' 'c' 'd']
 ['12' '13' '14' '15']
 ['0' '0' '0' '0']]
>>> ['a' 'b' 'c' 'd']
>>> c
>>> c
>>> [['b']
 ['13']]
>>> [['b' 'c']
 ['13' '14']
 ['0' '0']]


In [29]:
# iteration
a = [['a', 'b', 'c', 'd'], [12, 13, 14, 15], [0, 0, 0, 0]]
arr = np.array(a)
print(">>", arr.__repr__())
print(">>>", arr.__str__())

#basic iteration : prints rows
print(">>")
for i in arr:
    print('i=', i)
#element iteration : prints elements by flattening a n-dim matrix                                  
print(">>>")
for i in arr.flatten(): # or arr.ravel()
    print( i, end=' ')
print()

a2= np.arange(6).reshape(2,3)
print(">>",a2)
for i in a2:
    i[...]*=2
print(">>>",a2)
# we are accesing the items elementwise and not index. but we can still modify it.

#np.nditer(arr) :similar to flatten(), but memory efficient since it
# generates a much smaller iterator object insted of creating a whole new flattened list.                                                               
#(but this won't provide the inplace-editing feature in default mode, its read only kind-of thing)                             
print(">>")
for i in np.nditer(arr):
    print(i,end=' ')
print()
#npiter can also be used to traverse columnwise.
print(">>>")
for i in np.nditer(arr, order='F'):
    print(i,end=' ')
print()
# as i said , nditor does not have inplace editing , coz of generator , well, i was lying. we can do inlace editing(LOL)
for i in np.nditer(arr, order='F',op_flags=['readwrite']):
    i[...]= str(i)*2
print(">>>",arr)





>> array([['a', 'b', 'c', 'd'],
       ['12', '13', '14', '15'],
       ['0', '0', '0', '0']], dtype='<U2')
>>> [['a' 'b' 'c' 'd']
 ['12' '13' '14' '15']
 ['0' '0' '0' '0']]
>>
i= ['a' 'b' 'c' 'd']
i= ['12' '13' '14' '15']
i= ['0' '0' '0' '0']
>>>
a b c d 12 13 14 15 0 0 0 0 
>> [[0 1 2]
 [3 4 5]]
>>> [[ 0  2  4]
 [ 6  8 10]]
>>
a b c d 12 13 14 15 0 0 0 0 
>>>
a 12 0 b 13 0 c 14 0 d 15 0 
>>> [['aa' 'bb' 'cc' 'dd']
 ['12' '13' '14' '15']
 ['00' '00' '00' '00']]
>>> ['aa' 'bb' 'cc' 'dd' '12' '13' '14' '15' '00' '00' '00' '00']
>>> [['aa' 'bb' 'cc' 'dd']
 ['12' '13' '14' '15']
 ['00' '00' '00' '00']]
