In [2]:
import numpy as np

In [13]:
ang_degrees     = np.array([0, 30, 45, 60, 90, 120, 180])
ang_radians     = ang_degrees * np.pi / 180
ang_radians2    = np.radians(ang_degrees)  # similar to ang_radians
ang_degrees2    = np.degrees(ang_radians)  # just another function for comfy transformation

sines_deg       = np.sin(ang_degrees)  # this gives wrong values 
sines_rad       = np.sin(ang_radians)  # this gives right values sinces np.sine(angle in radians)        

coses           = np.cos(ang_radians)
tans            = np.tan(ang_radians)

sin_invs        = np.arcsin(sines_rad)
cos_invs        = np.arccos(coses)
tan_invs        = np.arctan(tans)
#sinh/cosh/tanh/ their inverses also available

#===================================
print(">>>",ang_degrees)
print(">>>",ang_radians)
print(">>>",ang_radians2)
print(">>>",ang_degrees2)

print(">>>",sines_deg)

print(">>>",sines_rad)
print(">>>",coses)
print(">>>",tans)
print(">>>",sin_invs)
print(">>>",cos_invs)
print(">>>",tan_invs)


>>> [  0  30  45  60  90 120 180]
>>> [0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]
>>> [0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]
>>> [  0.  30.  45.  60.  90. 120. 180.]
>>> [ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]
>>> [0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 8.66025404e-01 1.22464680e-16]
>>> [ 1.00000000e+00  8.66025404e-01  7.07106781e-01  5.00000000e-01
  6.12323400e-17 -5.00000000e-01 -1.00000000e+00]
>>> [ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.73205081e+00
  1.63312394e+16 -1.73205081e+00 -1.22464680e-16]
>>> [0.00000000e+00 5.23598776e-01 7.85398163e-01 1.04719755e+00
 1.57079633e+00 1.04719755e+00 1.22464680e-16]
>>> [0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]
>>> [ 0.00000000e+00  5.23598776e-01  7.85398163e-01  1.04719755e+00
  1.57079633e+00 -1.04719755e+00 -1.22464680e-16]


In [25]:
weights = np.array([50, 50.7, 52.5, 58, 55.63, 73.25, 49.5, 45])
median = np.median(weights)
mean = np.mean(weights)
#mode   = no function defined
std_dev = np.std(weights)
variance = np.var(weights)

#===============================
print(">>>", weights)
print(">>>", median)
print(">>>", mean)
print(">>>", std_dev)
print(">>>", variance)


>>> [50.   50.7  52.5  58.   55.63 73.25 49.5  45.  ]
>>> 51.6
>>> 54.3225
>>> 8.052773978574091
>>> 64.84716875


In [6]:
filename = r'C:\Users\anshs\00ANSH_PYTHON\04-10-18 [1] NUMPY\new_records.csv'              
data = np.genfromtxt(filename, delimiter=',', dtype=int,usecols=3)
print(data)
#gen from text parameters:
#skip_header=1   >>> skips first row
#usecols=(1,2,..)>>> shows data for only those columns
#... many

#since np.genfromtext(...) gave a numpy array , therefore:
print(data.shape)

median = np.median(data)
mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)

#===============================
print(">>>", data)
print(">>>", median)
print(">>>", mean)
print(">>>", std_dev)
print(">>>", variance)



[22 18 25 21 25 22 21 28 24]
(9,)
>>> [22 18 25 21 25 22 21 28 24]
>>> 22.0
>>> 22.88888888888889
>>> 2.7666443551086073
>>> 7.65432098765432
